### ISSUE TITLE
where cause an empty sequence

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sixty-north/asq#5]
```
What steps will reproduce the problem?
>>> from asq.initiators import query
>>> x = query([1,2,3,4,5]).where(lambda x: x % 2 == 0)
>>> x.count()
2
>>> x.first()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/entity/python-2.7.3/lib/python2.7/site-packages/asq-1.0-py2.7.egg/asq/queryables.py", line 1486, in first
    return self._first() if predicate is None else self._first_predicate(predicate)
  File "/usr/local/entity/python-2.7.3/lib/python2.7/site-packages/asq-1.0-py2.7.egg/asq/queryables.py", line 1492, in _first
    raise ValueError("Cannot return first() from an empty sequence.")
ValueError: Cannot return first() from an empty sequence.

What is the expected output? What do you see instead?
I think no error because I don't get error in C#

What version of the product are you using? On what operating system?
asq 1.0 (replace queryables.py with 1.0.1 branch's queryables.py) / Python 
2.7.3 on cygwin

Please provide any additional information below.
```

Original issue reported on code.google.com by `nekom...@gmail.com` on 29 May 2012 at 6:56

**Comment by scls19fr** [comment]
Same/similar issue here

```python
from asq.initiators import query
a = [1, 2, 3, 4, 5, 6]
res = query(a).where(lambda x: x>2)

print(list(res))
print(list(res))
```

displays

```
[3, 4, 5, 6]
[]
```

**Comment by scls19fr** [comment]
Pinging @sixty-north

**Comment by scls19fr** [comment]
Pinging @rob-smallshire
Any idea?
it seems that `Queryable` can be consumed only once.

**Comment by rob-smallshire** [comment]
There are trade-offs to be made here. Results in `py-linq` can be consumed more than once because it caches (*i.e.* takes a copy of!) the source data into an internal list (possibly multiple times!). This is obviously hugely problematic for very large or unbounded data series, which `asq` will handle without problems.

First of all, notice that `py_linq` isn't re-executing the query, it's just regurgitating the results it gave you last time:

```
>>> from py_linq import Enumerable
>>> a = [1, 2, 3, 4, 5, 6]
>>> res = Enumerable(a).where(lambda x: x>2)
>>> print(list(res))
[3, 4, 5, 6]
>>> a.append(7)
>>> a
[1, 2, 3, 4, 5, 6, 7]
>>> print(list(res))
[3, 4, 5, 6]
```

Now let's look at memory usage on identical queries. First `py_linq`:

```
>>> # 3.5 MB
>>> from py_linq import Enumerable
>>> # 3.7 MB
>>> res = Enumerable(range(1000000)).where(lambda x: x>2)
>>> # ... After about 5 seconds pause ...
>>> # 455 MB
>>> for _ in res:
...     pass
... 
>>> # 76 MB
>>> # Total CPU time 9.42 seconds
```

With `asq`:

```
>>> # 3.5 MB
>>> from asq.initiators import query
>>> # 4.1 MB
>>> res = query(range(1000000)).where(lambda x: x>2).select(lambda x: x*x).distinct()
>>> # (instantaneously)
>>> # 4.4 MB
>>> for _ in res:
>>>     pass
>>> # 19.3 MB
>>> # Total CPU time 0.94 seconds
```

Given that `py_linq` is just storing a list internally, you may as well just force evaluation of the result into a list with `asq`:

```
>>> res = query(range(1000000)).where(lambda x: x>2).to_list()
```

As you can see, `asq` is substantially more efficient in terms of both performance and memory than `py_linq`, being about 10x faster and using 1% of the memory on this simple test. Obtaining results multiple times is simply a case of forcing evaluation into a list.  The `asq` packages gives you this choice, whereas `py_linq` will consume resources whether you like it or not.

The great thing is, you can choose which to use.

**Comment by scls19fr** [comment]
Thanks @rob-smallshire for your great explanations about differences between `asq` and `py_linq`.

**Comment by viralogic** [comment]
Pinging @rob-smallshire, @scls19fr 

Hi everyone. Thanks for your analysis of py_linq. It is muchly appreciated.

Rob is correct. The iterable wrapped by Enumerable class is cached, but this only occurs when the elements in the iterable are iterated over. Here is my implementation of the __iter__ method.

![image](https://user-images.githubusercontent.com/10284720/28039155-7abd6554-657e-11e7-8f91-78f84aea42a6.png)

I implemented this purely so the Enumerable could be iterated over more than once. I believe this is a feature and not a bug. Hence why there are what I call executing methods (ie. count, sum, max, min) and non-executing statements.

Rob, in your example, I noticed that you said that it took 5 seconds to execute:

![image](https://user-images.githubusercontent.com/10284720/28039184-956c1198-657e-11e7-875a-a957cda223f1.png)

I have duplicated your code in a Python console and do not see where it takes over 5 seconds to execute Enumerable(range(1000000)).where(lambda x: x>2). In my testing, the res variable is returned instantaneously also. The where method was designed to be non-executing. Also, can you please provide me with the tooling that you used to monitor memory size of objects? Sorry, but I am not familiar with what you were to track memory size interactively in the console and would like to try and replicate what you have seen.

Again, thanks for your feedback on py_linq. I would like to learn and improve on areas that need it.
